GET http://localhost:3000/bank-accounts

###
GET http://localhost:3000/bank-accounts/ce669d21-4fa4-47bb-8918-e657b809910a

###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
    "account_number": "2222-22"
}

###
PATCH http://localhost:3000/bank-accounts/123
Content-Type: application/json

{
    "account_number": 1234
}

###
DELETE http://localhost:3000/bank-accounts/123

###
POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
    "from": "1111-11",
    "to": "2222-22",
    "amount": 100
}